### Taps ###

tap "FelixKratz/formulae"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mono0926/license-plist"
tap "nikitabobko/tap"
tap "xcodesorg/made"
tap "yonaskolb/beak", "https://github.com/yonaskolb/Beak.git"

### Brews (Packages/Formulae) ###

brew "bat"
brew "bat-extras"
brew "borders"
brew "btop"
brew "bundletool"
brew "cmatrix"
brew "curl"
brew "direnv"
brew "docker"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpegthumbnailer"
brew "flake8"
brew "fx"
brew "fzf"
brew "gcc"
brew "gd"
brew "gh"
brew "git"
brew "git-delta"
brew "git-flow"
brew "glow"
brew "gnutls"
brew "go"
brew "harfbuzz"
brew "htop"
brew "httpie"
brew "hyperkey"
brew "imagemagick"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jq"
brew "kdoctor"
brew "lazygit"
brew "luarocks"
brew "mas"
brew "mint"
brew "neovim"
brew "node"
brew "openjdk@17"
brew "otree"
brew "pandoc"
brew "pkg-config"
brew "poppler"
brew "powerlevel10k"
brew "python"
brew "raycast"
brew "ripgrep"
brew "sevenzip"
brew "shellcheck"
brew "shfmt"
brew "spicetify-cli"
brew "stylua"
brew "swiftformat"
brew "swiftgen"
brew "swiftlint"
brew "swiftlint"
brew "thefuck"
brew "tlrc"
brew "tmux"
brew "tree"
brew "webp"
brew "wget"
brew "xcodesorg/made/xcodes"
brew "yazi"
brew "zoxide"
brew "zsh"

### Not used at the moment ####

# brew "fastlane"
# brew "koekeishiya/formulae/skhd"
# brew "koekeishiya/formulae/yabai"
# brew "spotify-tui"
# brew "zellij"

### Zsh plugins are loaded via zinit ###

# brew "zsh-autosuggestions"
# brew "zsh-syntax-highlighting"
# brew "zsh-vi-mode"

### Casks (Applications) ###

cask "aerospace"
cask "alfred"
cask "android-file-transfer"
cask "android-studio"
cask "appcleaner"
cask "basictex"
cask "charles"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "gimp"
cask "kitty"
cask "logi-options+"
cask "obsidian"
cask "proxyman"
cask "rectangle"
cask "signal"
cask "silicon-info"
cask "telegram"
cask "via"
cask "vlc"
cask "whatsapp"
cask "xcodes"
cask "zen-browser"

### Not used at the moment ###

# cask "1password"
# cask "amethyst"
# cask "brave-browser"
# cask "clockify"
# cask "fork"
# cask "google-drive"
# cask "postman"

# Mac App Store command line interface
mas "AusweisApp", id: 948660805
mas "Developer", id: 640199958
mas "Messenger", id: 1480068668
mas "Playgrounds", id: 1496833156
mas "Xcode", id: 497799835
