# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

### Plugins
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light jeffreytse/zsh-vi-mode
zinit light Aloxaf/fzf-tab
zinit ice depth=1; zinit light romkatv/powerlevel10k

### Oh-my-zsh plugins
zinit snippet OMZP::command-not-found

# Load tab completions
autoload -U compinit && compinit

# -q is for quiet; actually run all the `compdef's saved before `compinit` call
# (`compinit' declares the `compdef' function, so it cannot be used until
# `compinit' is ran; Zinit solves this via intercepting the `compdef'-calls and
# storing them for later use with `zinit cdreplay')
zinit cdreplay -q

### Keybindings
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

### History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space # Ignore commands starting with space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

### Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:complete:z:*' fzf-preview 'eza -1 --color=always $realpath'

### Custom functions

# Shell wrapper for yazi https://yazi-rs.github.io/docs/quick-start
# We suggest using this y shell wrapper that provides the abiility to change
# the current working directory when exiting yazi.
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

# Better copy. Creates missing folder when trying to copy with cp
bcp() {
  mkdir -p $(dirname "$2") && cp "$1" "$2"
}

### Compress PDF files
compresspdf() {
  gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dPDFSETTINGS=/${3:-"ebook"} -dCompatibilityLevel=1.4 -sOutputFile="$2" "$1"
}

### Create directory and cd into it
mkcd() {
  mkdir -p "$1" && cd "$1"
}

### Github Copilot CLI
ghc() {
  if exists gh; then
    gh copilot explain "$1"
  else
    echo "\ngh is not installed. Please install it via Homebrew. Make sure GH Copilot CLI is setup.\n"
  fi
}

### Path extended
typeset -U path # Remove duplicates from path array. Lowercase path is an array. Uppercase PATH is a scalar.
path=(
  "$HOMEBREW_PREFIX/opt/curl/bin" # If you need to have curl first in your PATH, otherwise it will be overriden by /usr/bin/curl
  $path
  "/Users/paule/Library/Android/sdk/platform-tools"
  "/usr/bin"
  "/bin"
  "/usr/sbin"
  "/sbin"
  "/usr/local/bin"
  "$HOMEBREW_PREFIX/bin"
  "/Users/paule/.spicetify"
  "/usr/local/opt/ruby/bin"
  "$HOME/Library/Android/sdk/cmdline-tools/latest/bin"
  "/opt/homebrew/opt/openjdk@17/bin"
  "/Library/TeX/texbin"
)

### Exports
export HOMEBREW_CASK_OPTS="--no-quarantine"
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'" # Used for bat tool (alternative to cat, installed via homebrew)
export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home"
export EDITOR="$HOMEBREW_PREFIX/bin/nvim"
export DYLD_FALLBACK_LIBRARY_PATH="$(brew --prefix)/lib:$DYLD_FALLBACK_LIBRARY_PATH"
export BAT_THEME="Catppuccin Macchiato"
export NULLCMD=bat
export OBSIDIAN_VAULT="$HOME/Dev/Git/SecondBrain/obsidian/Paulaner/"
export FZF_DEFAULT_OPTS=" \
  --color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
  --color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
  --color=marker:#b7bdf8,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
  --color=selected-bg:#494d64 \
  --multi \
  --height 50%"
# For compilers to find curl you may need to set:
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/curl/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/curl/include"
# For pkg-config to find curl you may need to set:
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/curl/lib/pkgconfig"

### Aliases
alias ls='ls --color'
alias vim='nvim'
alias lg='lazygit'
alias l='eza -lhUu --git --group-directories-first --icons --no-user'
alias ld='eza -lhUu --git --group-directories-first --icons --no-user -s=mod -r'
alias ll='eza -alhUu --git --group-directories-first --icons --no-user'
alias lld='eza -alhUu --git --group-directories-first --icons --no-user -s=mod -r'
alias lll='eza -alThUu --git --group-directories-first --icons --level=5 --no-user'
alias llld='eza -alThUu --git --group-directories-first --icons --level=5 --no-user -s=mod -r'
alias tree1='tree -L 1'
alias tree2='tree -L 2'
alias tree3='tree -L 3'
alias tree4='tree -L 4'
alias tree5='tree -L 5'
alias tree6='tree -L 6'
alias cd='z'
alias cdi='__zoxide_zi'
alias c='clear'
alias vimdiff='nvim -d'
alias icat='kitten icat'
alias printenvs='<<<${(F)path}'

### Shell integrations
eval "$(fzf --zsh)"

### Zoxide for autocompletions in the terminal
eval "$(zoxide init zsh)"

### Thefuck for auto-correction
eval $(thefuck --alias fuck)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh. Keep at the bottom of ~/.zshrc.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
